### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/Cconv_merged.json'

### ISSUE THREAD

**Issue by cingtiye** [XiaoMi/C3KG#2]
非常感谢贵公司的开源！

请问在google云盘中的`Cconv_merge.json`是不是就是paths.cfg下的`Cconv = ./data/Cconv_merged.json`？
因为在跑的时候报错没有`./data/Cconv_merged.json`，所以我想是不是应该把paths.cfg下的`Cconv = ./data/Cconv_merged.json`改成
`Cconv = ./data/Cconv_merge.json`。

![image](https://user-images.githubusercontent.com/32251546/191151683-fd1a362b-ae20-4a0c-8c1e-8d563e6504e4.png)

非常希望得到您的回复！谢谢~

**Comment by xxAkuya** [comment]
![image](https://user-images.githubusercontent.com/90362376/194696801-3ce729bf-5f3d-48e0-910c-5a56cbf487d2.png)
为什么调试的时候这句话会报错，查看了path文件，并没有找到以下文件
![image](https://user-images.githubusercontent.com/90362376/194696846-0f543250-7ae2-41e6-8396-4f01e573e61a.png)

**Comment by cingtiye** [comment]
> ![image](https://user-images.githubusercontent.com/90362376/194696801-3ce729bf-5f3d-48e0-910c-5a56cbf487d2.png) 为什么调试的时候这句话会报错，查看了path文件，并没有找到以下文件 ![image](https://user-images.githubusercontent.com/90362376/194696846-0f543250-7ae2-41e6-8396-4f01e573e61a.png)

这个是运行代码生产的
![image](https://user-images.githubusercontent.com/32251546/194696956-54ed7d1f-33a2-4649-9381-20b478b332ca.png)
